export const NEXTORA_DATA = {
  overview: {
    total: 2840,
    scope1: { tco2e: 412, percent: 14.5, color: "#EF4444" },
    scope2: { tco2e: 1065, percent: 37.5, color: "#F59E0B" },
    scope3: { tco2e: 1363, percent: 48, color: "#3B82F6" },
    esgScore: 61,
    target2030: { current: 2840, goal: 1420, percent: 50 },
  },
  deadlines: [
    { name: "CSRD Report", date: "March 30, 2026", status: "In Progress" },
    { name: "CDP Response", date: "August 1, 2026", status: "Not Started" },
    { name: "GRI Report", date: "December 15, 2026", status: "Not Started" },
  ],
  targets: [
    {
      id: "A",
      name: "50% Scope 1+2 Reduction by 2030",
      baseline: 1477,
      goal: 738,
      status: "On Track",
      progress: 68,
      year: 2030,
    },
    {
      id: "B",
      name: "Net-Zero Scope 1 by 2028",
      baseline: 412,
      goal: 0,
      status: "At Risk",
      progress: 40,
      year: 2028,
    },
    {
      id: "C",
      name: "Scope 3 Flight Emissions -40% by 2030",
      baseline: 420,
      goal: 252,
      status: "On Track",
      progress: 10,
      year: 2030,
    },
    {
      id: "D",
      name: "Scope 3 Supply Chain Engagement: 80%",
      baseline: 35,
      goal: 80,
      status: "On Track",
      progress: 45,
      year: 2026,
    },
  ],
  offsets: [
    {
      id: 1,
      name: "Rondônia Forest Protection",
      type: "Reforestation / REDD+",
      location: "Amazon, Brazil",
      cost: 12.5,
      purchased: 500,
      tags: ["Biodiversity", "Livelihood"],
      image: "https://images.unsplash.com/photo-1516026672322-bc52d61a55d5?auto=format&fit=crop&q=80&w=600",
    },
    {
      id: 2,
      name: "Enel Geothermal, El Salvador",
      type: "Renewable energy",
      location: "La Paz, El Salvador",
      cost: 18,
      purchased: 300,
      tags: ["Renewable", "Community"],
      image: "https://images.unsplash.com/photo-1548611716-e522383c3cce?auto=format&fit=crop&q=80&w=600",
    },
    {
      id: 3,
      name: "Biochar Soil Carbon, Uganda",
      type: "Soil carbon sequestration",
      location: "Kasese District, Uganda",
      cost: 22,
      purchased: 0,
      tags: ["Agriculture", "Long-term"],
      image: "https://images.unsplash.com/photo-1605371720490-b19b25110eb9?auto=format&fit=crop&q=80&w=600",
    },
  ],
  hierarchy: [
    {
      name: "Scope 1 (Direct)",
      color: "#EF4444",
      children: [
        { name: "Gas Heating", size: 180 },
        { name: "Vehicle Fleet", size: 195 },
        { name: "Refrigerant", size: 37 },
      ],
    },
    {
      name: "Scope 2 (Energy)",
      color: "#F59E0B",
      children: [
        { name: "Grid Electricity", size: 1040 },
        { name: "Video Streaming", size: 25 },
      ],
    },
    {
      name: "Scope 3 (Value Chain)",
      color: "#3B82F6",
      children: [
        { name: "Business Flights", size: 420 },
        { name: "Purchased Materials", size: 450 },
        { name: "Employee Commuting", size: 290 },
        { name: "Shipping/Logistics", size: 180 },
        { name: "Waste", size: 23 },
      ],
    },
  ],
};
